c_sd: 0.06
chla_lag: true
chla_lag_days: 1
climatology_pi90_multiplier: 4.0
cloud_cover_source: dynamical
da_localization: false
data_in_dir: !!python/object/apply:pathlib._local.PosixPath
- in/
decoder_autoregressive: false
decoder_include_static: true
decoder_last_chla: true
decoder_seq_len: 34
dropout_rate: 0.3
early_stopping_patience: 50
email: addelany@vt.edu
encoder_seq_len: 90
end_date_test: '2023-12-31'
end_date_train:
- '2022-12-31'
- '2025-12-31'
end_date_val: '2024-12-31'
f_horizon: 34
fine_tune: true
force_pos: false
forecast_data_file: !!python/object/apply:pathlib._local.PosixPath
- in/forecast_data/forecast_data_chla.nc
forecast_dir: !!python/object/apply:pathlib._local.PosixPath
- out/forecast/
gefs_local_file: !!python/object/apply:pathlib._local.PosixPath
- in/gefs/gefs_analysis_flare_stage3.nc
gefs_operational_local_file: !!python/object/apply:pathlib._local.PosixPath
- in/gefs/gefs_operational_stage2_35d_2020-10-01_2025-12-31.nc
gpu: false
h_sd: 0.02
head: CMAL
head_hidden_units: 16
head_n_distr: 1
hidden_units: 16
hydro_local_file: !!python/object/apply:pathlib._local.PosixPath
- in/hydro/usgs_discharge.nc
hydro_vars:
- river_discharge
include_forecast_uncertainty: false
lag_days: 0
lag_target: false
lead_times: 35d
learn_rate_fine: 0.001
learn_rate_pre: 0.001
log_transform_target: false
lstm_noAR_local_file: !!python/object/apply:pathlib._local.PosixPath
- in/lstm_noAR_chl/20260305_lstm_noAR_usgs-stack_CMAL_h64_preds.feather
max_date: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
- 1767139200000000000
- null
- null
- 10
mc_dropout: false
met_data_source: flare_s3_stage2
met_driver_lag_days: 1
min_date: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
- 1601510400000000000
- null
- null
- 10
model_date: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
- 1791417600000000000
- null
- null
- 10
model_id: 20261008_ed_chlalast_vera_CMAL_h16_e90d34
model_type: encoder_decoder
n_en_gridmet: 1
n_epochs_fine: 1000
n_epochs_pre: 5
n_samples: 100
n_segs: 1
obs_local_file: !!python/object/apply:pathlib._local.PosixPath
- in/observations/obs.nc
obs_uncertainty_n_mc_samples: 1000
overwrite_training_outputs: false
pre_train: false
produce_ensembles: false
recurrent_dropout_rate: 0
residual_state_transfer: false
root_dir: null
savoy_data_file: !!python/object/apply:pathlib._local.PosixPath
- in/savoy_dataset/model inputs and outputs.txt
savoy_metadata_file: !!python/object/apply:pathlib._local.PosixPath
- in/savoy_dataset/site information.txt
seed: 4
site_ids_to_include:
- fcre
site_metadata_url: https://raw.githubusercontent.com/LTREB-reservoirs/vera4cast/main/vera4cast_field_site_metadata.csv
sites_to_include:
- vera4cast
spatial_idx_name: site_id
stackpoole_data_file: !!python/object/apply:pathlib._local.PosixPath
- in/stackpoole_dataset/wrtds_resids_ewi.csv
stackpoole_metadata_file: !!python/object/apply:pathlib._local.PosixPath
- in/stackpoole_dataset/site_metadata.csv
start_date_test: '2023-01-01'
start_date_train:
- '2020-10-01'
- '2025-01-01'
start_date_val: '2024-01-01'
store_forecasts: true
store_raw_states: true
target_data_file: !!python/object/apply:pathlib._local.PosixPath
- in/observations/obs_forecast_sites.csv
target_url: https://amnh1.osn.mghpcc.org/bio230121-bucket01/vera4cast/targets/project_id=vera4cast/duration=P1D/daily-insitu-targets.csv.gz
temp_obs_sd: 0.5
time_idx_name: time
train_dir: !!python/object/apply:pathlib._local.PosixPath
- out/model_train/20261008_stage2_d34_chlalast_h16/
training_data_dir: !!python/object/apply:pathlib._local.PosixPath
- in/training_data/20261008_stage2_d34_chlalast_h16/
umal_extend_batch: false
umal_tau_max: 0.75
umal_tau_min: 0.25
update_c: true
update_h: false
use_obs_uncertainty_in_loss: false
vera4cast_chla_url: https://amnh1.osn.mghpcc.org/bio230121-bucket01/vera4cast/targets/project_id=vera4cast/duration=P1D/daily-insitu-targets.csv.gz
vera4cast_inflow_site_map:
    tubr: fcre
vera4cast_inflow_url: https://amnh1.osn.mghpcc.org/bio230121-bucket01/vera4cast/targets/project_id=vera4cast/duration=P1D/daily-inflow-targets.csv.gz
vera4cast_model_id: chla_lstm_ed
verbose: true
weight_loss: false
weight_threshold: 22
weight_value: 5
x_vars:
- downward_long_wave_radiation_flux_surface
- downward_short_wave_radiation_flux_surface
- maximum_temperature_2m
- minimum_temperature_2m
- precipitation_surface
- temperature_2m
- total_cloud_cover_atmosphere
- wind_u_10m
- wind_v_10m
x_vars_static:
- pctcrop2019
- pctimp2019
- p_ags_2017
- n_ags_2017
- wwtpalldens
- elev
- rddens
- bfi
- runoff
y_vars:
- chla
