# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:


name: baseline-forecasts

jobs:
  docker:
    runs-on: ubuntu-latest
    container: rqthomas/vera-rocker:latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate forecasts
        shell: Rscript {0}
        run: |
          source("inflow_aed.R")
